# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Kenneth Chow - Welcome
description: >- # this means to ignore newlines until "baseurl:"
  Personal page
baseurl: "" # the subpath of the site
url: "https://kennethchow.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-C9ZJF29VKD"

header:
  pages:
    - name: Home
      slug: /
    - name: Work

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: kennethchowsk@gmail.com
      link: mailto:kennethchowsk@gmail.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/kenneth-chow/
    - name: GitHub
      link: http://github.com/kennethchow

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
