# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Kenneth Chow
tagline:          'San Francisco based Data Scientist'
description:      'New opportunities and networking welcome. <a href="https://www.linkedin.com/in/kenneth-chow/" target="_blank">LinkedIn</a>'
url:              https://kennethchow.github.io/
baseurl:          /

author:
  name:           'Kenneth Chow'
  url:            https://www.linkedin.com/in/kenneth-chow/

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/kennethchow           
